version: '3.8'

services: 
  app:
    build: .
    container_name: multiplayer-modes-app
    env_file: 
      - .env
    ports: 
      - "${PORT}:${PORT}"
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports: 
      - "6379:6379"
    
  mongo: 
    image: mongo:latest
    container_name: mongo_db
    ports: 
      - "27017:27017"
    environment: 
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - mongo-delta:/data/db
    
volumes:
  mongo-delta: